before_install:
- npm install -g grunt-cli
language: node_js
node_js:
- '0.10'
notifications:
  email: false
env:
  global:
  - secure: I2KRh7wgkr0wbTzIy7JdkiNXSmRCcvnTvLXhRLYbPJmv4yXEQZ4tEeecyMQiNDkUHFBMsRmz9DeP25xA63ipmustO+l+O908Dy6i6JZPjfcBZn+QxpObePh06ahMgBSDYhWgpHz+oC/vy+w+CsNbjijg521SeDW5aSgNe8bo4PY=
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  on:
    all_branches: true
    tags: true
  api_key:
    secure: CabaQ3I+CPCs39ZRfqqWe3mtuvD12EZ8+aNVIpKFg9v1GB5x9eYZrYn1W42TwnKX9e3ikKR96waUnpzuBg8kf5I8O9sT86YsZp3ga76GM9PPlcTUGJrkC1FZmIHV6G1DDGv92bST5N/keJVB45wAhsj0PXxpGMH0TV+PjfUCYSo=
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
sudo: false
cache:
  directories:
  - node_modules
